### ISSUE TITLE
feature request: spanish translation

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/dearneighbors#14]
As a member of the denver community I would love to have this project in spanish so we can share it with our hispanic community ❤️

**Comment by dviramontes** [comment]
We can try to use libraries like https://www.i18next.com/ to potentially open it up for other communities as well.

**Comment by dviramontes** [comment]
Here is a nice little tutorial on how to use it: https://www.i18next.com/overview/getting-started

**Comment by anotherpatrickcollins** [comment]
I highly agree with this. Would love a translation.

**Comment by anotherpatrickcollins** [comment]
@azuniga1 Hey Ariel, sorry for the delay. This is the issue you can grab for the spanish translation so people know you're working on it. 

I'll attach the pdf here, and make another comment with a text file of the website content for translation!
[Dear Neighbors_live.pdf](https://github.com/codefordenver/dearneighbors/files/4950576/Dear.Neighbors_live.pdf)

**Comment by anotherpatrickcollins** [comment]
Here's the website text as a text file too!
[dear neighbors website text.txt](https://github.com/codefordenver/dearneighbors/files/4950581/dear.neighbors.website.text.txt)

**Comment by azuniga1** [comment]
Thank you I will take a look and start working on the translation

**Comment by azuniga1** [comment]
I have the Spanish pdf done, should push it to the main branch or separate branch ?

**Comment by anotherpatrickcollins** [comment]
Took this translation and edited it into the final InDesign file to create a Spanish version that matched the English one. Uploaded and linked it below the English version on the site. 

If we get a translation of the site text I think we'll make a new site and link to the Spanish site, rather than just have the Spanish translation of the file!
[Querido Vecino.pdf](https://github.com/codefordenver/dearneighbors/files/5229334/Querido.Vecino.pdf)

**Comment by dviramontes** [comment]
Looks great! Thank you!
